### ISSUE TITLE
Couple of problems in Ubuntu 15.10

### ISSUE THREAD

**Issue by MHM5000** [buttercup-pw/buttercup#88] opened 2016-10-03 12:05 UTC
Hi,
Here's the [gist](https://gist.github.com/MHM5000/3b13bcd855061d5ccde13fc9892df1e5) of the whole error.

**Comment by perry-mitchell** [comment] 2016-10-03 14:29
This is a duplicate of #25 - I've mentioned your gist there, thank you.

**Closed by perry-mitchell** 2016-10-03 14:29 UTC
