### ISSUE TITLE
Importing from KeePass archive fails

### ISSUE THREAD

**Issue by vectorsize** [buttercup-pw/buttercup#170] opened 2017-03-09 21:57 UTC
Hello, been trying to use buttercup but the import keeps on failing with my keepass file (generated with KeepasX v2.0.3 for OSX.)

here's the message I get: 
`Importing from KeePass archive failed: Cannot read property 'getHistory' of undefined`

<img width="1062" alt="screen shot 2017-03-09 at 22 51 46" src="https://cloud.githubusercontent.com/assets/1661889/23772487/68dd57ea-051b-11e7-95c5-32d4c2b7e58e.png">

Got the error with the new v0.10.0 and the previous release.
I tried debugging with the source code but never got very far, the file seems to be properly opened and decrypted, this happens right after, perhaps it's something known? I didn't see any reference to it in the open issues.

**Comment by perry-mitchell** [comment] 2017-03-10 05:07
Thanks for filing an issue.

As we need to reproduce this, could you please try creating a new archive with your version of keepass, add some passwords to it (fake data) and see if that imports?

If it fails as well, you could send us that file and it's password for us to debug with. If it works, there may be some complication with your archive's data and the keepass library we use (we didn't write the keepass parsing logic). On that note, you could try using the library to see if the problem is on the Buttercup side or the keepass side.

**Comment by vectorsize** [comment] 2017-03-10 07:21
Ok, a quick test with a fresh database with 3 dummy passwords worked, I'm going to perform some more tests with the buttercup source and come back with more details.

**Comment by vectorsize** [comment] 2017-03-10 08:10
Ok, I've found the problem, this is a problem with passwords with line breaks, the parsing breaks [here](https://github.com/buttercup-pw/buttercup-importer/blob/master/source/importers/KeePass2Importer.js#L47) when calling `entry.setProperty(friendlyKey, actualValue);`

I'll close this issue and reopen a new one in the `buttercup-importer` repo.

**Comment by perry-mitchell** [comment] 2017-03-17 10:02
This is still occurring with 0.10.1:

![image](https://cloud.githubusercontent.com/assets/3869469/24038327/9569f914-0b09-11e7-85c9-53e7801f7698.png)

**Comment by sallar** [comment] 2017-03-17 10:38
@perry-mitchell lol I didn't do that :D

**Comment by sallar** [comment] 2017-03-17 19:49
Finally fixed in 0.11.1. Closing this now.

**Closed by sallar** 2017-03-17 19:49 UTC
Labels: Priority: High, Status: Available, Type: Bug

**Comment by vectorsize** [comment] 2017-03-17 19:54
Yes indeed!! great success, thanks a lot @sallar and @perry-mitchell 🤓✌️

**Comment by perry-mitchell** [comment] 2017-03-17 21:42
Thanks for the patience @vectorsize !
