### ISSUE TITLE
Confirm password when creating new archive

### ISSUE THREAD

**Issue by Jonas-Drotleff** [buttercup-pw/buttercup#158] opened 2017-01-31 19:19 UTC
When creating a new archive and giving it a master password, the user should be asked to confirm the password (simply two textfields) as user tent to choose a complicated and long password as a master password and spellings are very likely. Or at least make it possible to print out the password clear (letters instead of *)

**Comment by sallar** [comment] 2017-01-31 19:21
Thanks, but this is a duplicate of #35, #62 and #78. This is prioritized and will be done soon :)

**Closed by sallar** 2017-01-31 19:21 UTC

**Comment by Jonas-Drotleff** [comment] 2017-01-31 19:23
Oups, sorry 😬

**Comment by sallar** [comment] 2017-01-31 19:23
@Jonas-Drotleff No problem at all :)
