### ISSUE TITLE
Cmd + A for editing titles and group names

### ISSUE THREAD

**Issue by BehrouzIX** [buttercup-pw/buttercup#34] opened 2016-01-30 12:48 UTC
Cmd + A doesn't work if you want to edit the titles or group names.

**Comment by sallar** [comment] 2016-02-03 18:18
Cmd+A works everywhere as far as I tried. Please re-open if proven otherwise.

**Comment by naitian** [comment] 2016-02-03 19:06
Cmd+A seems to work when running using electron from the command line (i.e. `electron .`), but doesn't work (for me, also) when running the alpha release downloaded and installed from the packages page... I'm not sure what's up with that.

**Comment by perry-mitchell** [comment] 2016-02-03 19:18
I can confirm this @naitian - The installed version doesn't respond to Cmd+A, whereas the development version does.

**Comment by sallar** [comment] 2016-02-03 19:32
I just double checked the issue:
The installed version didn’t support CMD+A because the app was lacking system menus. As a result of issue #45 being resolved, the `Edit` menu is in place now and CMD+A works as expected.
We’ll leave this issue open until the next version has been released.

**Comment by sallar** [comment] 2016-11-08 12:03
Closed by #92

**Closed by sallar** 2016-11-08 12:03 UTC
Labels: Priority: High, Status: Available, Type: Bug
